openapi: 3.0.3
info:
  title: API
  version: 0.0.0
  description: API documentation.
servers:
  - url: /
tags:
  - name: Probes
paths:
  /probe/liveness:
    get:
      operationId: getLiveness
      tags:
        - Probes
      responses:
        '200':
          description: Service is alive.
          content:
            text/plain; charset=utf-8:
              schema:
                type: string
                enum:
                  - OK
  /probe/readiness:
    get:
      operationId: getReadiness
      tags:
        - Probes
      responses:
        '200':
          description: All dependencies are ready.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/GetReadinessResponseBody'
        '503':
          description: One or more dependencies are not ready.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/GetReadinessResponseBody'
              example:
                databaseMain: NOT_READY
                databaseAnalytics: OK
                databaseLogging: NOT_READY
                service1: OK
                service2: OK
components:
  schemas:
    GetReadinessResponseBody:
      type: object
      required:
        - databaseMain
        - databaseAnalytics
        - databaseLogging
        - service1
        - service2
      properties:
        databaseMain:
          $ref: '#/components/schemas/ReadinessStatus'
        databaseAnalytics:
          $ref: '#/components/schemas/ReadinessStatus'
        databaseLogging:
          $ref: '#/components/schemas/ReadinessStatus'
        service1:
          $ref: '#/components/schemas/ReadinessStatus'
        service2:
          $ref: '#/components/schemas/ReadinessStatus'
    ReadinessStatus:
      type: string
      enum:
        - OK
        - NOT_READY
