// Package docs Code generated by swaggo/swag. DO NOT EDIT
package docs

import "github.com/swaggo/swag"

const docTemplate = `{
    "schemes": {{ marshal .Schemes }},
    "swagger": "2.0",
    "info": {
        "description": "{{escape .Description}}",
        "title": "{{.Title}}",
        "contact": {},
        "version": "{{.Version}}"
    },
    "host": "{{.Host}}",
    "basePath": "{{.BasePath}}",
    "paths": {
        "/v1/liveness": {
            "get": {
                "description": "Check service health return \"OK\"",
                "produces": [
                    "text/plain"
                ],
                "tags": [
                    "Health"
                ],
                "summary": "Check service health",
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/health.livenessStatus"
                        }
                    }
                }
            }
        },
        "/v1/readiness": {
            "get": {
                "description": "Check connection to database and other services",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Health"
                ],
                "summary": "Check service readiness",
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/health.readinessResponseUp"
                        }
                    },
                    "503": {
                        "description": "Service Unavailable",
                        "schema": {
                            "$ref": "#/definitions/health.readinessResponseDown"
                        }
                    }
                }
            }
        }
    },
    "definitions": {
        "health.livenessStatus": {
            "type": "string",
            "enum": [
                "OK"
            ],
            "x-enum-varnames": [
                "livenessStatusOk"
            ]
        },
        "health.readinessResponseDown": {
            "type": "object",
            "properties": {
                "status": {
                    "allOf": [
                        {
                            "$ref": "#/definitions/health.readinessStatus"
                        }
                    ],
                    "example": "DOWN"
                }
            }
        },
        "health.readinessResponseUp": {
            "type": "object",
            "properties": {
                "status": {
                    "allOf": [
                        {
                            "$ref": "#/definitions/health.readinessStatus"
                        }
                    ],
                    "example": "UP"
                }
            }
        },
        "health.readinessStatus": {
            "type": "string",
            "enum": [
                "UP",
                "DOWN"
            ],
            "x-enum-varnames": [
                "readinessStatusUp",
                "readinessStatusDown"
            ]
        }
    }
}`

// SwaggerInfo holds exported Swagger Info so clients can modify it
var SwaggerInfo = &swag.Spec{
	Version:          "1.0.0",
	Host:             "",
	BasePath:         "/api",
	Schemes:          []string{},
	Title:            "Go with Gin and Zerolog",
	Description:      "This is a sample server.",
	InfoInstanceName: "swagger",
	SwaggerTemplate:  docTemplate,
	LeftDelim:        "{{",
	RightDelim:       "}}",
}

func init() {
	swag.Register(SwaggerInfo.InstanceName(), SwaggerInfo)
}
